language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - sudo apt-get install -qq python-gdal
  - pip install -r requirements.txt
  - pip install pytest
# command to run tests
script:
  - python setup.py install
  - pytest

jobs:
  include:
    - stage: coverage
      python: "3.8"
      install:
        - sudo apt-get install -qq python-gdal
        - pip install -r requirements.txt
        - pip install pytest pytest-cov coveralls
      script: pytest --cov=rivamap/
      after_success: 
        - coveralls
